-- 
--  Copyright 2023; Réal Demers.
-- 
--  Licensed under the Apache License, Version 2.0 (the "License");
--  you may not use this file except in compliance with the License.
--  You may obtain a copy of the License at
-- 
--     http://www.apache.org/licenses/LICENSE-2.0
-- 
--  Unless required by applicable law or agreed to in writing, software
--  distributed under the License is distributed on an "AS IS" BASIS,
--  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
--  See the License for the specific language governing permissions and
--  limitations under the License.
-- 
--  DDL for the staging database.
--  Simple database definition.

-- BEGIN.
--
DROP TABLE IF EXISTS INVENTORY;
DROP TABLE IF EXISTS PRODUCT;
DROP TABLE IF EXISTS PERSON;

CREATE TABLE PERSON (
    PERSON_ID  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FIRST_NAME VARCHAR(64)    NOT NULL,
    LAST_NAME  VARCHAR(64)    NOT NULL,
    BALANCE    DECIMAL(10, 2) NOT NULL,
    CONSTRAINT PERSON_FIRST_LAST_NAME_UK UNIQUE (FIRST_NAME, LAST_NAME)
);

CREATE TABLE PRODUCT (
    PRODUCT_ID  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CODE        VARCHAR(64)    NOT NULL,
    DESCRIPTION VARCHAR(128)   NOT NULL,
    PRICE       DECIMAL(10, 2) NOT NULL,
    CONSTRAINT PRODUCT_CODE_UK UNIQUE (CODE)
);

CREATE TABLE INVENTORY (
    INVENTORY_ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PRODUCT_ID   INTEGER NOT NULL,
    QTY          INTEGER NOT NULL,
    CONSTRAINT INVENTORY_PRODUCT_UK UNIQUE (PRODUCT_ID),
    CONSTRAINT INVENTORY_PRODUCT_FK FOREIGN KEY (PRODUCT_ID)
        REFERENCES PRODUCT (PRODUCT_ID)
);
--
-- END.